BEGIN_STRING = '<BEGIN>'
END_STRING = '<END>'
TAG_END_STRING = '<TAG_END>'

SP_STRINGS_LIST = [BEGIN_STRING, END_STRING, TAG_END_STRING]
TAGS = []

EXTRA_TOKEN_LIST = [s for s in SP_STRINGS_LIST]

EXTRA_TOKEN_TOKENIZER_INDEX_DICT = {
    BEGIN_STRING: 1,
    END_STRING: 2,
    TAG_END_STRING: 3,
}

EXTRA_TOKEN_PREDICT_BIAS_DICT = {
    BEGIN_STRING: 0,
    END_STRING: 1,
    TAG_END_STRING: 2,
}

EXTRA_TOKEN_2D_POS_DICT = {
    BEGIN_STRING: [1001, 1001, 1001, 1001],
    END_STRING: [1002, 1002, 1002, 1002],
    TAG_END_STRING: [1003, 1003, 1003, 1003],
}
